{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/axpcore\/axperror\/cancelled"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError\/cancelled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If the operation was cancelled"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"title":"AXPError.cancelled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:7AXPCore8AXPErrorO9cancelledyA2CmF","modules":[{"name":"AXPCore"}]},"hierarchy":{"paths":[["doc:\/\/AXPCore\/documentation\/AXPCore","doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError"]]},"references":{"doc://AXPCore/documentation/AXPCore":{"role":"collection","title":"AXPCore","abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore","kind":"symbol","type":"topic","url":"\/documentation\/axpcore"},"doc://AXPCore/documentation/AXPCore/AXPError/cancelled":{"role":"symbol","title":"AXPError.cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[{"type":"text","text":"If the operation was cancelled"}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError\/cancelled","kind":"symbol","type":"topic","url":"\/documentation\/axpcore\/axperror\/cancelled"},"doc://AXPCore/documentation/AXPCore/AXPError":{"role":"symbol","title":"AXPError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXPError"}],"abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"type":"text","text":"across the network."}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AXPError"}],"url":"\/documentation\/axpcore\/axperror"}}}