{"abstract":[{"type":"text","text":"A textual description of the error."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/description"},"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"AXPCore"}],"externalID":"s:7AXPCore8AXPErrorO11descriptionSSvp","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/description"]}],"references":{"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore":{"url":"\/documentation\/axpcore","title":"AXPCore","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError/description":{"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/description","abstract":[{"type":"text","text":"A textual description of the error."}],"url":"\/documentation\/axpcore\/axperror\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol","title":"description"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AXPError","kind":"identifier"}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError","navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","title":"AXPError","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"type":"text","text":"across the network."}],"role":"symbol","kind":"symbol"}}}