{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/internalerror"]}],"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","interfaceLanguage":"swift"},"abstract":[{"text":"If internal error","type":"text"}],"sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","title":"AXPError.internalError","modules":[{"name":"AXPCore"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"externalID":"s:7AXPCore8AXPErrorO13internalErroryA2CmF"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore":{"abstract":[{"text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore","kind":"symbol","title":"AXPCore","url":"\/documentation\/axpcore","role":"collection"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError/internalError":{"type":"topic","abstract":[{"type":"text","text":"If internal error"}],"kind":"symbol","role":"symbol","title":"AXPError.internalError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"url":"\/documentation\/axpcore\/axperror\/internalerror","identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AXPError"}],"abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"text":"across the network.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPError","kind":"identifier"}],"kind":"symbol","title":"AXPError","identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError","url":"\/documentation\/axpcore\/axperror"}}}