{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/axpcore\/axperror\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"}],"externalID":"s:7AXPCore8AXPErrorO13internalErroryA2CmF","modules":[{"name":"AXPCore"}],"title":"AXPError.internalError","roleHeading":"Case","role":"symbol"},"abstract":[{"type":"text","text":"If internal error"}],"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"sections":[],"references":{"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AXPError","kind":"identifier"}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError","navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","title":"AXPError","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"type":"text","text":"across the network."}],"role":"symbol","kind":"symbol"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore":{"url":"\/documentation\/axpcore","title":"AXPCore","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError/internalError":{"abstract":[{"type":"text","text":"If internal error"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","title":"AXPError.internalError","role":"symbol","url":"\/documentation\/axpcore\/axperror\/internalerror"}}}