{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"identifier":{"url":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/internalerror"]}],"metadata":{"symbolKind":"case","role":"symbol","externalID":"s:7AXPCore8AXPErrorO13internalErroryA2CmF","title":"AXPError.internalError","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"modules":[{"name":"AXPCore"}]},"abstract":[{"type":"text","text":"If internal error"}],"kind":"symbol","references":{"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError/internalError":{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","kind":"symbol","title":"AXPError.internalError","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror\/internalerror","abstract":[{"text":"If internal error","type":"text"}]},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore":{"title":"AXPCore","kind":"symbol","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","abstract":[{"text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user.","type":"text"}],"url":"\/documentation\/axpcore","role":"collection","type":"topic"},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError":{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol","title":"AXPError","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPError","kind":"identifier"}],"navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"text":" ","type":"text"},{"text":"across the network.","type":"text"}]}}}